version: 2
registries:
version: 2
registries:
  k9-felles:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/k9-felles
    username: x-access-token
    password: ${{secrets.PAT}}
  k9-format:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/k9-format
    username: x-access-token
    password: ${{secrets.PAT}}
  fp-nare:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/fp-nare
    username: x-access-token
    password: ${{secrets.PAT}} 
  fp-tidsserie:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/fp-tidsserie
    username: x-access-token
    password: ${{secrets.PAT}} 
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    registries:
      - k9-felles
      - k9-format
      - fp-nare
      - fp-tidsserie
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 15

