version: '3.7'
services:
  postgres:
    image: $POSTGRES_IMAGE
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    ports:
      - "5433:5432"
    volumes:
      - ./lokalutvikling/postgres-init:/docker-entrypoint-initdb.d/
    container_name: postgres_kalkulus