version: '3.7'
services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=fpkalkulus
      - POSTGRES_USER=fpkalkulus
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d/
    container_name: postgres_kalkulus
