CREATE TABLE IF NOT EXISTS REGEL_INPUT_KOMPRIMERING
(
    REGEL_INPUT_HASH              VARCHAR(32) NOT NULL,
    REGEL_INPUT_JSON              TEXT NOT NULL
);

create UNIQUE index PK_REGEL_INPUT_KOMPRIMERING on REGEL_INPUT_KOMPRIMERING (REGEL_INPUT_HASH);
alter table REGEL_INPUT_KOMPRIMERING add constraint PK_REGEL_INPUT_KOMPRIMERING
    primary key using index PK_REGEL_INPUT_KOMPRIMERING;
create sequence if not exists SEQ_REGEL_INPUT_KOMPRIMERING increment by 50 minvalue 1000000;

alter TABLE REGEL_SPORING_PERIODE
    ADD REGEL_INPUT_HASH VARCHAR(32);

alter table REGEL_SPORING_PERIODE add constraint FK_REGEL_SPORING_PERIODE_10
    foreign key (REGEL_INPUT_HASH) references REGEL_INPUT_KOMPRIMERING (REGEL_INPUT_HASH);
