ALTER TABLE IF EXISTS REGEL_SPORING_GRUNNLAG
DROP COLUMN IF EXISTS REGEL_EVALUERING;

ALTER TABLE IF EXISTS REGEL_SPORING_GRUNNLAG
DROP COLUMN IF EXISTS REGEL_INPUT;

ALTER TABLE IF EXISTS REGEL_SPORING_PERIODE
DROP COLUMN IF EXISTS REGEL_EVALUERING;

ALTER TABLE IF EXISTS REGEL_SPORING_PERIODE
DROP COLUMN IF EXISTS REGEL_INPUT;
