ALTER TABLE IF EXISTS FAKTA_AKTOER
ADD COLUMN IF NOT EXISTS SKAL_BEREGNES_SOM_MILITAER BOOLEAN;
comment on column FAKTA_AKTOER.SKAL_BEREGNES_SOM_MILITAER is 'Sier om bruker har hatt og skal beregnes som militær/siviltjeneste';

ALTER TABLE IF EXISTS FAKTA_ARBEIDSFORHOLD
ADD COLUMN IF NOT EXISTS HAR_LONNSENDRING_I_BEREGNINGSPERIODEN BOOLEAN;
comment on column FAKTA_ARBEIDSFORHOLD.HAR_LONNSENDRING_I_BEREGNINGSPERIODEN is 'Sier om arbeidsforholdet har hatt lønnsendring i beregningsperioden';
