ALTER TABLE IF EXISTS BG_PR_STATUS_OG_ANDEL
ADD COLUMN IF NOT EXISTS KILDE VARCHAR(100) DEFAULT 'PROSESS_START';

comment on column BG_PR_STATUS_OG_ANDEL.KILDE is 'Angir kilde/opphav for andel';

UPDATE BG_PR_STATUS_OG_ANDEL
SET KILDE = 'PROSESS_START';

ALTER TABLE IF EXISTS BG_PR_STATUS_OG_ANDEL
ALTER COLUMN KILDE SET NOT NULL;
