INSERT INTO REFUSJON_GYLDIGHETSPERIODE (ID, BG_REFUSJON_OVERSTYRING_ID, FOM, TOM)
select nextval('SEQ_REFUSJON_GYLDIGHETSPERIODE'), ID, FOM, '9999-12-31 00:00:00' from BG_REFUSJON_OVERSTYRING
where FOM is not null and not exists
      (select 1 from REFUSJON_GYLDIGHETSPERIODE
where REFUSJON_GYLDIGHETSPERIODE.BG_REFUSJON_OVERSTYRING_ID = BG_REFUSJON_OVERSTYRING.ID);

ALTER TABLE BG_REFUSJON_OVERSTYRING DROP COLUMN FOM;
