-- FK BG_REFUSJON_OVERSTYRING
CREATE INDEX IDX_BR_OVERSTYRING_01 ON bg_refusjon_overstyring (br_overstyringer_id);

ALTER TABLE BG_REFUSJON_OVERSTYRING ADD CONSTRAINT FK_BR_OVERSTYRINGER_01 FOREIGN KEY (BR_OVERSTYRINGER_ID) REFERENCES BG_REFUSJON_OVERSTYRINGER (ID);

-- PK BG_AKTIVITET_OVERSTYRING
CREATE UNIQUE INDEX PK_BG_AKTIVITET_OVERSTYRING on BG_AKTIVITET_OVERSTYRING (ID);

ALTER TABLE BG_AKTIVITET_OVERSTYRING ADD CONSTRAINT PK_BA_OVERSTYRING PRIMARY KEY USING INDEX PK_BG_AKTIVITET_OVERSTYRING;

-- FK BG_AKTIVITET_OVERSTYRING
CREATE INDEX IDX_BA_OVERSTYRING_01 ON BG_AKTIVITET_OVERSTYRING (BA_OVERSTYRINGER_ID);

ALTER TABLE BG_AKTIVITET_OVERSTYRING ADD CONSTRAINT FK_BA_OVERSTYRINGER_01 FOREIGN KEY (BA_OVERSTYRINGER_ID) REFERENCES BG_AKTIVITET_OVERSTYRINGER (ID);
