ALTER TABLE FAKTA_ARBEIDSFORHOLD DROP COLUMN IF EXISTS FK_ER_TIDSBEGRENSET;
ALTER TABLE FAKTA_ARBEIDSFORHOLD DROP COLUMN IF EXISTS FK_HAR_MOTTATT_YTELSE;
ALTER TABLE FAKTA_ARBEIDSFORHOLD DROP COLUMN IF EXISTS FK_HAR_LONNSENDRING_I_BEREGNINGSPERIODEN;


ALTER TABLE FAKTA_ARBEIDSFORHOLD ADD ER_TIDSBEGRENSET_KILDE VARCHAR(100);
comment on column FAKTA_ARBEIDSFORHOLD.ER_TIDSBEGRENSET_KILDE is 'Kilde til vurdering av om arbeidsforhold er tidsbegrenset';
ALTER TABLE FAKTA_ARBEIDSFORHOLD ADD HAR_MOTTATT_YTELSE_KILDE VARCHAR(100);
comment on column FAKTA_ARBEIDSFORHOLD.HAR_MOTTATT_YTELSE_KILDE is 'Kilde til vurdering av om det er mottatt ytelse for arbeidsforhold';
ALTER TABLE FAKTA_ARBEIDSFORHOLD ADD HAR_LONNSENDRING_I_BEREGNINGSPERIODEN_KILDE VARCHAR(100);
comment on column FAKTA_ARBEIDSFORHOLD.HAR_LONNSENDRING_I_BEREGNINGSPERIODEN_KILDE is 'Kilde til vurdering av om arbeidsforhold har lønnsendring i beregningsperioden';

UPDATE FAKTA_ARBEIDSFORHOLD
SET ER_TIDSBEGRENSET_KILDE='SAKSBEHANDLER'
WHERE ER_TIDSBEGRENSET is not null;
UPDATE FAKTA_ARBEIDSFORHOLD
SET HAR_MOTTATT_YTELSE_KILDE='SAKSBEHANDLER'
WHERE HAR_MOTTATT_YTELSE is not null;
UPDATE FAKTA_ARBEIDSFORHOLD
SET HAR_LONNSENDRING_I_BEREGNINGSPERIODEN_KILDE='SAKSBEHANDLER'
WHERE HAR_LONNSENDRING_I_BEREGNINGSPERIODEN is not null;

ALTER TABLE FAKTA_AKTOER DROP COLUMN IF EXISTS FK_ER_NY_I_ARBEIDSLIVET_SN;
ALTER TABLE FAKTA_AKTOER DROP COLUMN IF EXISTS FK_ER_NYOPPSTARTET_FL;
ALTER TABLE FAKTA_AKTOER DROP COLUMN IF EXISTS FK_HAR_FL_MOTTATT_YTELSE;
ALTER TABLE FAKTA_AKTOER DROP COLUMN IF EXISTS FK_MOTTAR_ETTERLONN_SLUTTPAKKE;
ALTER TABLE FAKTA_AKTOER DROP COLUMN IF EXISTS FK_SKAL_BEREGNES_SOM_MILITAER;

ALTER TABLE FAKTA_AKTOER ADD ER_NY_I_ARBEIDSLIVET_SN_KILDE VARCHAR(100);
comment on column FAKTA_AKTOER.ER_NY_I_ARBEIDSLIVET_SN_KILDE is 'Kilde til vurdering av om bruker er ny i arbeidslivet.';
ALTER TABLE FAKTA_AKTOER ADD ER_NYOPPSTARTET_FL_KILDE VARCHAR(100);
comment on column FAKTA_AKTOER.ER_NYOPPSTARTET_FL_KILDE is 'Kilde til vurdering av om bruker er nyoppstartet frilans.';
ALTER TABLE FAKTA_AKTOER ADD HAR_FL_MOTTATT_YTELSE_KILDE VARCHAR(100);
comment on column FAKTA_AKTOER.HAR_FL_MOTTATT_YTELSE_KILDE is 'Kilde til vurdering av om det er mottatt ytelse for frilans.';
ALTER TABLE FAKTA_AKTOER ADD MOTTAR_ETTERLONN_SLUTTPAKKE_KILDE VARCHAR(100);
comment on column FAKTA_AKTOER.MOTTAR_ETTERLONN_SLUTTPAKKE_KILDE is 'Kilde til vurdering av om bruker mottar etterlønn/sluttpakke.';
ALTER TABLE FAKTA_AKTOER ADD SKAL_BEREGNES_SOM_MILITAER_KILDE VARCHAR(100);
comment on column FAKTA_AKTOER.SKAL_BEREGNES_SOM_MILITAER_KILDE is 'Kilde til vurdering av om bruker skal beregnes som militær.';
ALTER TABLE FAKTA_AKTOER ADD SKAL_BESTEBEREGNES_KILDE VARCHAR(100);
comment on column FAKTA_AKTOER.SKAL_BESTEBEREGNES_KILDE is 'Kilde til vurdering av om bruker skal besteberegnes.';

UPDATE FAKTA_AKTOER
    SET ER_NY_I_ARBEIDSLIVET_SN_KILDE='SAKSBEHANDLER'
    WHERE ER_NY_I_ARBEIDSLIVET_SN is not null;
UPDATE FAKTA_AKTOER
SET ER_NYOPPSTARTET_FL_KILDE='SAKSBEHANDLER'
WHERE ER_NYOPPSTARTET_FL is not null;
UPDATE FAKTA_AKTOER
SET HAR_FL_MOTTATT_YTELSE_KILDE='SAKSBEHANDLER'
WHERE HAR_FL_MOTTATT_YTELSE is not null;
UPDATE FAKTA_AKTOER
SET MOTTAR_ETTERLONN_SLUTTPAKKE_KILDE='SAKSBEHANDLER'
WHERE MOTTAR_ETTERLONN_SLUTTPAKKE is not null;
UPDATE FAKTA_AKTOER
SET SKAL_BEREGNES_SOM_MILITAER_KILDE='SAKSBEHANDLER'
WHERE SKAL_BEREGNES_SOM_MILITAER is not null;
UPDATE FAKTA_AKTOER
SET SKAL_BESTEBEREGNES_KILDE='SAKSBEHANDLER'
WHERE SKAL_BESTEBEREGNES is not null;

drop table if exists FAKTA_VURDERING;
drop sequence if exists SEQ_FAKTA_VURDERING;
