-- Nye kolonner med boolske datatyper
alter table BG_ANDEL_ARBEIDSFORHOLD add TIDSBEGRENSET_ARBEIDSFORHOLD2 boolean;
alter table BG_ANDEL_ARBEIDSFORHOLD add LOENNSENDRING_I_PERIODEN2 boolean;
alter table BG_ARBEIDSTAKER_ANDEL add MOTTAR_YTELSE2 boolean;
alter table BG_FRILANS_ANDEL add MOTTAR_YTELSE2 boolean;
alter table BG_FRILANS_ANDEL add NYOPPSTARTET2 boolean;
alter table BG_PR_STATUS_OG_ANDEL add NY_I_ARBEIDSLIVET2 boolean;
alter table BG_PR_STATUS_OG_ANDEL add FASTSATT_AV_SAKSBEHANDLER2 boolean;

-- Migrere data
update BG_ANDEL_ARBEIDSFORHOLD set TIDSBEGRENSET_ARBEIDSFORHOLD2 = true where TIDSBEGRENSET_ARBEIDSFORHOLD = 'J';
update BG_ANDEL_ARBEIDSFORHOLD set TIDSBEGRENSET_ARBEIDSFORHOLD2 = false where TIDSBEGRENSET_ARBEIDSFORHOLD = 'N';
update BG_ANDEL_ARBEIDSFORHOLD set LOENNSENDRING_I_PERIODEN2 = true where LOENNSENDRING_I_PERIODEN = 'J';
update BG_ANDEL_ARBEIDSFORHOLD set LOENNSENDRING_I_PERIODEN2 = false where LOENNSENDRING_I_PERIODEN = 'N';
update BG_ARBEIDSTAKER_ANDEL set MOTTAR_YTELSE2 = true where MOTTAR_YTELSE = 'J';
update BG_ARBEIDSTAKER_ANDEL set MOTTAR_YTELSE2 = false where MOTTAR_YTELSE = 'N';
update BG_FRILANS_ANDEL set MOTTAR_YTELSE2 = true where MOTTAR_YTELSE = 'J';
update BG_FRILANS_ANDEL set MOTTAR_YTELSE2 = false where MOTTAR_YTELSE = 'N';
update BG_FRILANS_ANDEL set NYOPPSTARTET2 = true where NYOPPSTARTET = 'J';
update BG_FRILANS_ANDEL set NYOPPSTARTET2 = false where NYOPPSTARTET = 'N';
update BG_PR_STATUS_OG_ANDEL set NY_I_ARBEIDSLIVET2 = true where NY_I_ARBEIDSLIVET = 'J';
update BG_PR_STATUS_OG_ANDEL set NY_I_ARBEIDSLIVET2 = false where NY_I_ARBEIDSLIVET = 'N';
update BG_PR_STATUS_OG_ANDEL set FASTSATT_AV_SAKSBEHANDLER2 = true where FASTSATT_AV_SAKSBEHANDLER = 'J';
update BG_PR_STATUS_OG_ANDEL set FASTSATT_AV_SAKSBEHANDLER2 = false where FASTSATT_AV_SAKSBEHANDLER = 'N';

-- Slette gammel kolonne
alter table BG_ANDEL_ARBEIDSFORHOLD drop column TIDSBEGRENSET_ARBEIDSFORHOLD;
alter table BG_ANDEL_ARBEIDSFORHOLD drop column LOENNSENDRING_I_PERIODEN;
alter table BG_ARBEIDSTAKER_ANDEL drop column MOTTAR_YTELSE;
alter table BG_FRILANS_ANDEL drop column MOTTAR_YTELSE;
alter table BG_FRILANS_ANDEL drop column NYOPPSTARTET;
alter table BG_PR_STATUS_OG_ANDEL drop column NY_I_ARBEIDSLIVET;
alter table BG_PR_STATUS_OG_ANDEL drop column FASTSATT_AV_SAKSBEHANDLER;

-- Rename ny kolonne
alter table BG_ANDEL_ARBEIDSFORHOLD rename column TIDSBEGRENSET_ARBEIDSFORHOLD2 to TIDSBEGRENSET_ARBEIDSFORHOLD;
alter table BG_ANDEL_ARBEIDSFORHOLD rename column LOENNSENDRING_I_PERIODEN2 to LOENNSENDRING_I_PERIODEN;
alter table BG_ARBEIDSTAKER_ANDEL rename column MOTTAR_YTELSE2 to MOTTAR_YTELSE;
alter table BG_FRILANS_ANDEL rename column MOTTAR_YTELSE2 to MOTTAR_YTELSE;
alter table BG_FRILANS_ANDEL rename column NYOPPSTARTET2 to NYOPPSTARTET;
alter table BG_PR_STATUS_OG_ANDEL rename column NY_I_ARBEIDSLIVET2 to NY_I_ARBEIDSLIVET;
alter table BG_PR_STATUS_OG_ANDEL rename column FASTSATT_AV_SAKSBEHANDLER2 to FASTSATT_AV_SAKSBEHANDLER;
