ALTER TABLE REGEL_SPORING_GRUNNLAG
ADD COLUMN REGEL_EVALUERING_JSON TEXT;

ALTER TABLE REGEL_SPORING_GRUNNLAG
ADD COLUMN REGEL_INPUT_JSON TEXT;

comment on column REGEL_SPORING_GRUNNLAG.REGEL_EVALUERING_JSON is 'Regelevaluering/logging i json-format';
comment on column REGEL_SPORING_GRUNNLAG.REGEL_INPUT_JSON is 'Input til regelen i json-format';

ALTER TABLE REGEL_SPORING_PERIODE
ADD COLUMN REGEL_EVALUERING_JSON TEXT;

ALTER TABLE REGEL_SPORING_PERIODE
ADD COLUMN REGEL_INPUT_JSON TEXT;

comment on column REGEL_SPORING_PERIODE.REGEL_EVALUERING_JSON is 'Regelevaluering/logging i json-format';
comment on column REGEL_SPORING_PERIODE.REGEL_INPUT_JSON is 'Input til regelen i json-format';
