ALTER TABLE IF EXISTS BEREGNINGSGRUNNLAG
DROP COLUMN IF EXISTS REGELLOGG_SKJARINGSTIDSPUNKT;

ALTER TABLE IF EXISTS BEREGNINGSGRUNNLAG
DROP COLUMN IF EXISTS REGELLOGG_BRUKERS_STATUS;

ALTER TABLE IF EXISTS BEREGNINGSGRUNNLAG
DROP COLUMN IF EXISTS REGELINPUT_SKJARINGSTIDSPUNKT;

ALTER TABLE IF EXISTS BEREGNINGSGRUNNLAG
DROP COLUMN IF EXISTS REGELINPUT_BRUKERS_STATUS;

ALTER TABLE IF EXISTS BEREGNINGSGRUNNLAG
DROP COLUMN IF EXISTS REGELINPUT_PERIODISERING;

ALTER TABLE IF EXISTS BEREGNINGSGRUNNLAG_PERIODE
DROP COLUMN IF EXISTS REGEL_EVALUERING;

ALTER TABLE IF EXISTS BEREGNINGSGRUNNLAG_PERIODE
DROP COLUMN IF EXISTS REGEL_EVALUERING_FASTSETT;

ALTER TABLE IF EXISTS BEREGNINGSGRUNNLAG_PERIODE
DROP COLUMN IF EXISTS REGEL_INPUT;

ALTER TABLE IF EXISTS BEREGNINGSGRUNNLAG_PERIODE
DROP COLUMN IF EXISTS REGEL_INPUT_FASTSETT;

ALTER TABLE IF EXISTS BEREGNINGSGRUNNLAG_PERIODE
DROP COLUMN IF EXISTS REGEL_INPUT_FASTSETT_2;

ALTER TABLE IF EXISTS BEREGNINGSGRUNNLAG_PERIODE
DROP COLUMN IF EXISTS REGEL_EVALUERING_FASTSETT_2;

ALTER TABLE IF EXISTS BEREGNINGSGRUNNLAG_PERIODE
DROP COLUMN IF EXISTS REGEL_INPUT_VILKAR;

ALTER TABLE IF EXISTS BEREGNINGSGRUNNLAG_PERIODE
DROP COLUMN IF EXISTS REGEL_EVALUERING_VILKAR;

ALTER TABLE IF EXISTS BEREGNINGSGRUNNLAG_PERIODE
DROP COLUMN IF EXISTS REGEL_INPUT_OPPDATER_SVP;

ALTER TABLE IF EXISTS BEREGNINGSGRUNNLAG_PERIODE
DROP COLUMN IF EXISTS REGEL_EVALUERING_OPPDATER_SVP;
