DO
$do$
    BEGIN
        IF NOT EXISTS (SELECT FROM FAKTA_ARBEIDSFORHOLD) THEN
            ALTER TABLE IF EXISTS FAKTA_ARBEIDSFORHOLD
            DROP COLUMN IF EXISTS ARBEIDSFORHOLD_INTERN_ID;
            ALTER TABLE IF EXISTS FAKTA_ARBEIDSFORHOLD
                ADD COLUMN ARBEIDSFORHOLD_INTERN_ID UUID;
            ALTER TABLE IF EXISTS FAKTA_ARBEIDSFORHOLD
                DROP COLUMN IF EXISTS ARBEIDSFORHOLD_ORGNR;
            ALTER TABLE IF EXISTS FAKTA_ARBEIDSFORHOLD
                ADD COLUMN ARBEIDSFORHOLD_ORGNR VARCHAR(100);
            ALTER TABLE IF EXISTS FAKTA_ARBEIDSFORHOLD
                DROP COLUMN IF EXISTS ARBEIDSGIVER_AKTOR_ID;
            ALTER TABLE IF EXISTS FAKTA_ARBEIDSFORHOLD
                ADD COLUMN ARBEIDSGIVER_AKTOR_ID VARCHAR(100);
        END IF;
    END
$do$;
