name: Bygg pull request

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:11.5
          env:
            POSTGRES_USER: ftkalkulus_unit
            POSTGRES_PASSWORD: ftkalkulus_unit
            POSTGRES_DB: ftkalkulus_unit
          ports:
            - 5433:5432
          # needed because the postgres container does not provide a healthcheck
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build
        shell: bash
        run: |
          echo "Building $(echo $GITHUB_SHA | cut -c1-7)"
          mvn package --batch-mode --settings ./.github/.m2/settings.xml --file pom.xml -Dchangelist= -Dsha1=-$(TZ="Europe/Oslo" date +%Y%m%d%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DATASOURCE_HOST: localhost
          DATASOURCE_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
