name: Publish kontrakt
on:
  release:
    types: [published]

jobs:
  build:
    name: Bygg pull-request
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Publish artifacts
        shell: bash
        run: |
           mvn deploy -e --batch-mode --settings .github/.m2/settings.xml --file pom.xml -am -pl kontrakt,kalkulator -DtrimStackTrace=false -Dchangelist= -Dsha1= -Drevision=$NEW_VERSION -Dfile.encoding=UTF-8
        env:
          NEW_VERSION: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
